// <auto-generated />
using CPW211_MurderMystery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPW211_MurderMystery.Migrations
{
    [DbContext(typeof(MurderMysteryContext))]
    [Migration("20240225212621_AddedBlank")]
    partial class AddedBlank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPW211_MurderMystery.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("CharScript")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Characters", t =>
                        {
                            t.HasCheckConstraint("CK_Gender", "[Gender] IN ('Male', 'Female', 'No preference')");
                        });

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CharScript = "TDB",
                            Desc = "Father of Deimos, Phobos and Eden",
                            FullName = "Mars Olufemi",
                            Gender = "Male",
                            Occupation = "Cartographer",
                            ThemeId = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            CharScript = "TDB",
                            Desc = "Son of Mars, twin brother of Phobos, and elder brother of Eden.",
                            FullName = "Deimos Olufemi",
                            Gender = "Male",
                            Occupation = "Singer",
                            ThemeId = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            CharScript = "TDB",
                            Desc = "Son of Mars, twin brother of Deimos, and elder brother of Eden.",
                            FullName = "Phobos Olufemi",
                            Gender = "Male",
                            Occupation = "Locksmith",
                            ThemeId = 1
                        },
                        new
                        {
                            CharacterId = 4,
                            CharScript = "TDB",
                            Desc = "Adopted daughter of Mars and younger sister of Deimos and Phobos.",
                            FullName = "Eden Olufemi",
                            Gender = "Female",
                            Occupation = "Musician",
                            ThemeId = 1
                        },
                        new
                        {
                            CharacterId = 5,
                            CharScript = "TDB",
                            Desc = "Best friend of Phoebe.",
                            FullName = "Tahlia Collins",
                            Gender = "Female",
                            Occupation = "Gardener",
                            ThemeId = 1
                        },
                        new
                        {
                            CharacterId = 6,
                            CharScript = "TDB",
                            Desc = "Best friend of Tahlia.",
                            FullName = "Phoebe Mandrapilias",
                            Gender = "Female",
                            Occupation = "Painter",
                            ThemeId = 2
                        },
                        new
                        {
                            CharacterId = 7,
                            CharScript = "TDB",
                            Desc = "Wife/business partner of Walter and mother of Jamie.",
                            FullName = "Silvia Honey",
                            Gender = "Female",
                            Occupation = "Shop Owner",
                            ThemeId = 2
                        },
                        new
                        {
                            CharacterId = 8,
                            CharScript = "TDB",
                            Desc = "Husband/business partner of Silvia and father of Jamie.",
                            FullName = "Walter Honey",
                            Gender = "Male",
                            Occupation = "Shop Owner",
                            ThemeId = 2
                        },
                        new
                        {
                            CharacterId = 9,
                            CharScript = "TDB",
                            Desc = "Son of Walter and Silvia. Jamie was often babysat by Deimos as a child, and the two are still very close to this day. Jamie is also friends with Elliot, and often spends time in his library. Although, while the two enjoy talking, Jamie can’t say he knows much about Elliot personally.",
                            FullName = "Jamie Honey",
                            Gender = "Male",
                            Occupation = "Waiter",
                            ThemeId = 2
                        },
                        new
                        {
                            CharacterId = 10,
                            CharScript = "TDB",
                            Desc = "Friend of Jamie, but much of his past is a mystery to Jamie.",
                            FullName = "Elliot Perry",
                            Gender = "Male",
                            Occupation = "Librarian",
                            ThemeId = 2
                        });
                });

            modelBuilder.Entity("CPW211_MurderMystery.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("PlayerFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerGender")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerGender", "[PlayerGender] IN ('Male', 'Female', 'No preference')");
                        });

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PlayerFullName = "Player One",
                            PlayerGender = "Male"
                        },
                        new
                        {
                            PlayerId = 2,
                            PlayerFullName = "Person Two",
                            PlayerGender = "Female"
                        },
                        new
                        {
                            PlayerId = 3,
                            PlayerFullName = "User Three",
                            PlayerGender = "No preference"
                        });
                });

            modelBuilder.Entity("CPW211_MurderMystery.Theme", b =>
                {
                    b.Property<int>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThemeId"));

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            ThemeId = 1,
                            Summary = " ",
                            Title = "        "
                        },
                        new
                        {
                            ThemeId = 2,
                            Summary = "The town business tycoon is hosting a mascarade at her manor to celebrate her sons taking over of the family company.",
                            Title = "Mansion Party"
                        },
                        new
                        {
                            ThemeId = 3,
                            Summary = "This train is on a two hour nonstop trip to the next city over. As this specific route goes through the countryside, phone connections are spotty at best.",
                            Title = "Train"
                        });
                });

            modelBuilder.Entity("CPW211_MurderMystery.Character", b =>
                {
                    b.HasOne("CPW211_MurderMystery.Theme", "Theme")
                        .WithMany("Characters")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CPW211_MurderMystery.Theme", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
